In [1]:
using HTTP
using JSON

In [5]:
using CSV, DataFrames

In [17]:
using ProgressMeter

In [18]:
function google_distance_matrix_symmetric(locations::Array{String,1})
    if !haskey(ENV, "GAPI_KEY")
        error("Google API key not found.")
        return
    end
    key = ENV["GAPI_KEY"]

    locs = [foldl(replace, [", "=>"+", " "=>"+", ","=>"+"], init=s) for s in locations]

    N = length(locations)
    distancematrix = zeros(Int, N, N)
    @showprogress for i in 1:N
        for j in i+1:N
            s = locs[i]
            d = locs[j]
            url = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=$(s)&destinations=$(d)&key=$(key)"

            response = HTTP.request("GET", url)
            results = JSON.parse(String(response.body))["rows"][1]["elements"][1]

            if results["status"] != "OK"
                distancematrix[i,j] = -1
                distancematrix[j,i] = -1
                continue
            end

            distancematrix[i,j] = results["duration"]["value"]
            distancematrix[j,i] = results["duration"]["value"]
        end
    end

    return distancematrix
end;

In [27]:
state_list = CSV.read("../../data/geography/states.csv")

52×7 DataFrame. Omitted printing of 3 columns
│ Row │ state                │ abbrev │ fips  │ capital_city   │
│     │ String               │ String │ Int64 │ String         │
├─────┼──────────────────────┼────────┼───────┼────────────────┤
│ 1   │ Alabama              │ AL     │ 1     │ Montgomery     │
│ 2   │ Alaska               │ AK     │ 2     │ Juneau         │
│ 3   │ Arizona              │ AZ     │ 4     │ Phoenix        │
│ 4   │ Arkansas             │ AR     │ 5     │ Little Rock    │
│ 5   │ California           │ CA     │ 6     │ Sacramento     │
│ 6   │ Colorado             │ CO     │ 8     │ Denver         │
│ 7   │ Connecticut          │ CT     │ 9     │ Hartford       │
│ 8   │ Delaware             │ DE     │ 10    │ Dover          │
│ 9   │ District of Columbia │ DC     │ 11    │ Washington DC  │
│ 10  │ Florida              │ FL     │ 12    │ Tallahassee    │
⋮
│ 42  │ South Carolina       │ SC     │ 45    │ Columbia       │
│ 43  │ South Dakota         │ SD     │ 46    │ Pierre         │
│ 44  │ Tennessee            │ TN     │ 47    │ Nashville      │
│ 45  │ Texas                │ TX     │ 48    │ Austin         │
│ 46  │ Utah                 │ UT     │ 49    │ Salt Lake City │
│ 47  │ Vermont              │ VT     │ 50    │ Montpelier     │
│ 48  │ Virginia             │ VA     │ 51    │ Richmond       │
│ 49  │ Washington           │ WA     │ 53    │ Olympia        │
│ 50  │ West Virginia        │ WV     │ 54    │ Charleston     │
│ 51  │ Wisconsin            │ WI     │ 55    │ Madison        │
│ 52  │ Wyoming              │ WY     │ 56    │ Cheyenne       │

In [19]:
d1 = google_distance_matrix_symmetric(state_list.state[:])

Progress: 100%|█████████████████████████████████████████| Time: 0:02:26


52×52 Array{Int64,2}:
      0  255479   89850   26749  116722  …  140757   40475   51193   90341
 255479       0  220437  232522  205527     156716  246502  207165  177585
  89850  220437       0   69786   45071      85379  109183   96871   58301
  26749  232522   69786       0   97032     118153   44203   40289   67736
 116722  205527   45071   97032       0      57238  136161  116286   63471
  80541  196545   44583   57186   64475  …   75378   81836   60089   22556
  62969  260741  134005   72140  160247     153705   33325   57050  108375
  50547  256640  126982   60362  153961     149810   23341   53154  104479
  45186  252279  122181   54759  149159     145338   18870   48683  100008
  31818  277222  117131   54379  145405     164188   50482   74300  113771
  16528  259093  103673   36251  130651  …  146301   35224   56413   95885
     -1      -1      -1      -1      -1         -1      -1      -1      -1
 120629  177159   62084   97440   52119      36895  120897   90327   33962
   

In [25]:
dist_matrix_1 = DataFrame(d1)
rename!(dist_matrix_1, state_list.abbrev[:])

52×52 DataFrame. Omitted printing of 44 columns
│ Row │ AL     │ AK     │ AZ     │ AR     │ CA     │ CO     │ CT     │ DE     │
│     │ Int64  │ Int64  │ Int64  │ Int64  │ Int64  │ Int64  │ Int64  │ Int64  │
├─────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 1   │ 0      │ 255479 │ 89850  │ 26749  │ 116722 │ 80541  │ 62969  │ 50547  │
│ 2   │ 255479 │ 0      │ 220437 │ 232522 │ 205527 │ 196545 │ 260741 │ 256640 │
│ 3   │ 89850  │ 220437 │ 0      │ 69786  │ 45071  │ 44583  │ 134005 │ 126982 │
│ 4   │ 26749  │ 232522 │ 69786  │ 0      │ 97032  │ 57186  │ 72140  │ 60362  │
│ 5   │ 116722 │ 205527 │ 45071  │ 97032  │ 0      │ 64475  │ 160247 │ 153961 │
│ 6   │ 80541  │ 196545 │ 44583  │ 57186  │ 64475  │ 0      │ 104051 │ 99239  │
│ 7   │ 62969  │ 260741 │ 134005 │ 72140  │ 160247 │ 104051 │ 0      │ 16138  │
│ 8   │ 50547  │ 256640 │ 126982 │ 60362  │ 153961 │ 99239  │ 16138  │ 0      │
│ 9   │ 45186  │ 252279 │ 122181 │ 54759  │ 149159 │ 94878  │ 18898  │ 6375   │
│ 10  │ 31818  │ 277222 │ 117131 │ 54379  │ 145405 │ 104944 │ 66808  │ 54277  │
⋮
│ 42  │ 21264  │ 257666 │ 106442 │ 39020  │ 133420 │ 89608  │ 44450  │ 31919  │
│ 43  │ 72944  │ 186418 │ 72051  │ 50339  │ 88187  │ 33417  │ 86033  │ 82137  │
│ 44  │ 15373  │ 241601 │ 88549  │ 21127  │ 115528 │ 69324  │ 55640  │ 43930  │
│ 45  │ 44558  │ 229961 │ 49156  │ 31045  │ 76683  │ 43713  │ 100084 │ 88374  │
│ 46  │ 97146  │ 188379 │ 36572  │ 75980  │ 42415  │ 26967  │ 122962 │ 118436 │
│ 47  │ 76772  │ 265681 │ 143517 │ 82281  │ 166076 │ 109879 │ 15114  │ 29983  │
│ 48  │ 36803  │ 255946 │ 114996 │ 47574  │ 141974 │ 91280  │ 29094  │ 16564  │
│ 49  │ 140757 │ 156716 │ 85379  │ 118153 │ 57238  │ 75378  │ 153705 │ 149810 │
│ 50  │ 40475  │ 246502 │ 109183 │ 44203  │ 136161 │ 81836  │ 33325  │ 23341  │
│ 51  │ 51193  │ 207165 │ 96871  │ 40289  │ 116286 │ 60089  │ 57050  │ 53154  │
│ 52  │ 90341  │ 177585 │ 58301  │ 67736  │ 63471  │ 22556  │ 108375 │ 104479 │

In [26]:
CSV.write("state_dist_google.csv", dist_matrix_1);

In [30]:
city_list = map(s -> s.main_city * " " * s.abbrev, eachrow(state_list))

52-element Array{String,1}:
 "Birmingham AL"
 "Anchorage AK"
 "Phoenix AZ"
 "Little Rock AR"
 "Los Angeles CA"
 "Denver CO"
 "Bridgeport CT"
 "Wilmington DE"
 "Washington DC"
 "Jacksonville FL"
 "Atlanta GA"
 "Honolulu HI"
 "Boise ID"
 ⋮
 "Providence RI"
 "Charleston SC"
 "Sioux Falls SD"
 "Nashville TN"
 "Houston TX"
 "Salt Lake City UT"
 "Burlington VT"
 "Virginia Beach VA"
 "Seattle WA"
 "Charleston WV"
 "Milwaukee WI"
 "Cheyenne WY"

In [31]:
d2 = google_distance_matrix_symmetric(city_list)

Progress: 100%|█████████████████████████████████████████| Time: 0:02:15


52×52 Array{Int64,2}:
      0  251643   88168   20264  107594  …  137293   30569   40370   72784
 251643       0  218198  235143  218215     155146  243438  212150  188749
  88168  218198       0   69185   20471      78587  104263   97545   51227
  20264  235143   69185       0   88129     120504   39128   39255   54937
 107594  218215   20471   88129       0      63480  122790  108635   58761
  69707  194138   46334   50644   54551  …   71474   71027   55121    5907
  55665  262361  133770   70174  151562     155784   33157   51770   96361
  45767  257983  126711   60276  145239     151400   23937   47386   91977
  40071  254932  122978   54580  141506     148175   20400   44162   88753
  25764  271298  105427   45624  125160     158555   34743   61309   94046
   8240  253739   95863   28099  115025  …  140896   28007   43650   76388
     -1      -1      -1      -1      -1         -1      -1      -1      -1
 111423  181631   51245   93162   47990      28097  112154   91481   39046
   

In [33]:
dist_matrix_2 = DataFrame(d2)
col_names = map(s -> s.main_city * "." * s.abbrev, eachrow(state_list))
rename!(dist_matrix_2, col_names)

52×52 DataFrame. Omitted printing of 48 columns
│ Row │ Birmingham.AL │ Anchorage.AK │ Phoenix.AZ │ Little Rock.AR │
│     │ Int64         │ Int64        │ Int64      │ Int64          │
├─────┼───────────────┼──────────────┼────────────┼────────────────┤
│ 1   │ 0             │ 251643       │ 88168      │ 20264          │
│ 2   │ 251643        │ 0            │ 218198     │ 235143         │
│ 3   │ 88168         │ 218198       │ 0          │ 69185          │
│ 4   │ 20264         │ 235143       │ 69185      │ 0              │
│ 5   │ 107594        │ 218215       │ 20471      │ 88129          │
│ 6   │ 69707         │ 194138       │ 46334      │ 50644          │
│ 7   │ 55665         │ 262361       │ 133770     │ 70174          │
│ 8   │ 45767         │ 257983       │ 126711     │ 60276          │
│ 9   │ 40071         │ 254932       │ 122978     │ 54580          │
│ 10  │ 25764         │ 271298       │ 105427     │ 45624          │
⋮
│ 42  │ 24902         │ 265321       │ 112525     │ 44762          │
│ 43  │ 58067         │ 194219       │ 79277      │ 41823          │
│ 44  │ 10080         │ 240674       │ 87171      │ 18772          │
│ 45  │ 34942         │ 248469       │ 60534      │ 24516          │
│ 46  │ 96326         │ 181838       │ 36761      │ 78065          │
│ 47  │ 68623         │ 266456       │ 141354     │ 79963          │
│ 48  │ 40112         │ 265107       │ 125489     │ 57091          │
│ 49  │ 137293        │ 155146       │ 78587      │ 120504         │
│ 50  │ 30569         │ 243438       │ 104263     │ 39128          │
│ 51  │ 40370         │ 212150       │ 97545      │ 39255          │
│ 52  │ 72784         │ 188749       │ 51227      │ 54937          │

In [34]:
CSV.write("state_cities_dist_google.csv", dist_matrix_2);